# s3 storage config
storage:
  backend: s3
  s3:
    endpoint: ${PYROSCOPE_BUCKET_ENDPOINT}
    # region: ""
    bucket_name: ${PYROSCOPE_BUCKET_NAME}
    access_key_id: ${PYROSCOPE_ACCESS_KEY}
    secret_access_key: ${PYROSCOPE_SECRET_KEY}
    # insecure: true

metastore:
  address: 127.0.0.1:9095
  min_ready_duration: 1s
  # raft/index state must live in the persistent volume
  data_dir: /data/pyroscope/metastore/data
  raft:
    dir: /data/pyroscope/metastore/raft

distributor:
  ring:
    kvstore:
      store: inmemory

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    min_ready_duration: 1s

pyroscopedb:
  data_path: "/data/pyroscope"
